### ISSUE TITLE
ASP MVC Core UI identity / claims

### ISSUE THREAD

**Issue by fasteddys** [DamianEdwards/BlazorIdentity#1]
Hello Damian, can you also share some guidance on how to add Core Views for Identity with claims.

**Comment by DamianEdwards** [comment]
Can you expand on that a bit more as I'm not sure what you mean.

**Comment by fasteddys** [comment]
Hello @DamianEdwards not everyone is on Blazor, some older apps and for the developers who are using ASP MVC core views, theres no way to add user management with **claims** & Roles, and it would be helpful if there were some views we could leverage generically.

For e.g. company managers from one country (`manager role` + Claim `USA`) should not be able to see financials of company managers in a different country or vendor (`manager role` + Claim `UK`)

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-6.0
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-6.0

**Comment by DamianEdwards** [comment]
This isn't the place to talk about that, but I'm not aware of any limitation that means you can't use claims and roles together, in fact roles are based on claims under the covers. You should just be able to define policies that require both roles and specific claims.

As for versions of the Identity UI as MVC Views, I'm not planning on doing that in this repo (this is about Blazor).
